### ISSUE TITLE
Enhance landing page Responsiveness

### ISSUE THREAD

**Issue by mathanraj0601** [jy95/docusaurus-json-schema-plugin#151]
# Enhance responsiveness
I found that the text and description in the card of the landing page are text-aligned left for 
- JSON Schema Viewer / Editor
- Configurable
- Open source
I think It does not suit  the responsiveness of the website
I went through the code and made it text-align center below I will attach the screenshot comparing both:
### From:

![as1](https://github.com/jy95/docusaurus-json-schema-plugin/assets/98396468/1f02da21-e5fb-4fb4-8149-86ace7e59537)
### To;

![ss1](https://github.com/jy95/docusaurus-json-schema-plugin/assets/98396468/f1196d5d-696f-48e1-b91f-30bf18f97695)

### From:

![as2](https://github.com/jy95/docusaurus-json-schema-plugin/assets/98396468/ee8c33e5-941a-422b-b1bf-6ff4805b8f24)

### To:
![ss2](https://github.com/jy95/docusaurus-json-schema-plugin/assets/98396468/b739d65e-7f8d-4194-8ea6-4c41cd17cab9)

## Screen Width below 500px:
###From:

![as3](https://github.com/jy95/docusaurus-json-schema-plugin/assets/98396468/8ad2051c-7791-47f9-9f7b-eff17dfdd3d1)
###To:

![ss3](https://github.com/jy95/docusaurus-json-schema-plugin/assets/98396468/bc1c1bf6-4af4-4c25-bc89-f31061e44e5e)

**Comment by mathanraj0601** [comment]
If you like the above suggestion let me know and l like to contribute to this project : )

**Comment by jy95** [comment]
@mathanraj0601 You are welcome ;)

**Comment by mathanraj0601** [comment]
That's Great!  @jy95  Can you assign me so that i can start my work: )

**Comment by jy95** [comment]
@mathanraj0601 To build the website, you can apply same logic I did for the [Github actions script](https://github.com/jy95/docusaurus-json-schema-plugin/blob/main/.github/workflows/documentation.yml)

```bash
// Install lib 💻
npm install
// Build lib 🤖
npm run build
// Link lib 🔗
npm link
// Install website 💻
cd testsite
npm link docusaurus-json-schema-plugin --save
npm install --prefer-dedupe 
npm dedupe  
```

By doing a `npm start` in the `testsite` folder, you will be able to see a local version of the website.
As you can see, when you will create the MR ( such as https://github.com/jy95/docusaurus-json-schema-plugin/pull/150 ), you will have a preview website as well

**Comment by mathanraj0601** [comment]
Thank you @jy95  !!

**Comment by mathanraj0601** [comment]
yeah !! @jy95  Can you add it to hacktoberfest : )

**Comment by mathanraj0601** [comment]
Can i create a new issue to add the step involved in contribution.MD to setup the application locally following the step you mentioned?

**Comment by jy95** [comment]
@mathanraj0601 If you want. It might be better to put them in the readme of the testsite no ? (as people reads more readme.MD usually)

https://github.com/jy95/docusaurus-json-schema-plugin/blob/main/testsite/README.md

**Comment by mathanraj0601** [comment]
Yes !! @jy95

**Comment by mathanraj0601** [comment]
I have taken a long time to notice the setup to set up the application locally.
 Most of the projects put the development and other guides in the contribution itself. if possible can we add a simple section in the contribution.md as Development with the description " For development setup click here" with the link to that file ?
