### ISSUE TITLE
static file not being served in build

### ISSUE THREAD

**Issue by bwgjoseph** [jy95/docusaurus-json-schema-plugin#17]
I created a page to display all my json-schema (i,e /schema), I used `schema.mdx` file to display it

![image](https://user-images.githubusercontent.com/37484538/219557827-026ced3c-67cf-4233-b4c7-ae6aff296313.png)

In each of the `mdx` file, it looks something like this but importing different json file

```mdx
import JSONSchemaViewer from "@theme/JSONSchemaViewer"
import schema from "@site/static/schema/geo.json"

<JSONSchemaViewer schema={schema} />
```

In local development, it works as expected.

![image](https://user-images.githubusercontent.com/37484538/219557687-499d43c5-ee33-4211-89d9-8fb4050bd05f.png)

But when I build and serve it, it doesn't load the content

![image](https://user-images.githubusercontent.com/37484538/219557465-ddd910bd-f42c-4959-a005-13822083c3d6.png)

Not sure if it matters but I'm using `javascript` setup of `docusaurus` instead of `typescript`. 

Let me know if more information is required, or if this is a `docusaurus` issue, then I can redirect over to their repo.

Thanks!

**Comment by jy95** [comment]
Hello @bwgjoseph 

It is indeed weird it doesn't work for `javascript` as on my `typescript` documentation website, it works. 
( [mdx example](https://raw.githubusercontent.com/jy95/docusaurus-json-schema-plugin/main/testsite/docs/demo-viewer/array/tuples.mdx) & [example page](https://jy95.github.io/docusaurus-json-schema-plugin/docs/demo-viewer/array/tuples) )

As Docusaurus own website uses [`resolveJsonModule`](https://github.com/facebook/docusaurus/blob/main/website/tsconfig.json#L7) setting like mime, I think you can ask them their feedback.  
You can read https://docusaurus.io/docs/static-assets in the meantime and see if there is differences between require / import: 

```js
// import way
import schema from "@site/static/schema/geo.json"
// require way
require('@site/static/schema/geo.json').default}
```


Worthy to mention, release 1.2.0 is on the road - I can notify you when it is ready  ;)

**Comment by bwgjoseph** [comment]
Usually on first visit after a build will get this

![image](https://user-images.githubusercontent.com/37484538/219645582-cb58e103-d993-4b95-ad71-bde1d42842c6.png)

I did read that, and tried `require` before I reported

```js
import JSONSchemaViewer from "@theme/JSONSchemaViewer"
var schema = require('@site/static/schema/geo.json')

<JSONSchemaViewer schema={schema} />
```

And I just tried

```js
import JSONSchemaViewer from "@theme/JSONSchemaViewer"
const schema = require('@site/static/schema/geo.json').default

<JSONSchemaViewer schema={schema} />
```

Both way does not work too. Still getting the `loading...` screen

> Worthy to mention, release 1.2.0 is on the road - I can notify you when it is ready ;)

Sure! Thanks for creating this plugin.

**Comment by bwgjoseph** [comment]
hey, I managed to solve it (see https://github.com/facebook/docusaurus/issues/8676#issuecomment-1434967330) (i think)
