### ISSUE TITLE
JSONSchemaViewer colors palette override

### ISSUE THREAD

**Issue by manuelscurti** [jy95/docusaurus-json-schema-plugin#324]
Hi there! thanks for this wonderful plugin :)

Any hint on how to customize the colors used by the JSONSchemaViewer React component and override the ones given by docusaurus?

thanks!

**Comment by jy95** [comment]
Hello @manuelscurti, thanks ;)

Good question. I didn't tried this yet - would be curious about it.
Some hint could be : 

- https://docusaurus.io/docs/styling-layout#styling-your-site-with-infima
- https://infima.dev/
- https://infima.dev/docs/utilities/colors

The plugin uses at least the following things from Docusaurus color palette :

- classes `alert alert--info` for the collapse component ( https://infima.dev/docs/components/alert#info )
- `--ifm-color-primary` for the text
- `--ifm-background-color` for the background
- `--ifm-menu-color-background-active` for hovering
- `--ifm-color-secondary-darkest` for `constant`
- `--ifm-color-danger` for `required`
- `--ifm-color-primary-darker` for `writeOnly`
- `--ifm-color-info-darker` for `readOnly`
- `--ifm-color-warning` for `deprecated`

Maybe start with the [Global styles](https://docusaurus.io/docs/styling-layout#global-styles) approach - the documentation website has a [custom.css](https://github.com/jy95/docusaurus-json-schema-plugin/blob/main/testsite/src/css/custom.css) you can play with it . I have a Netlify set up as it is quite convenient to see visual changes in MR
